name: learning-od-step-by-step
dependencies:
  - python=3.9.12
  - jupyter=1.0.0
  - matplotlib=3.5.2
  - numpy=1.23.5
  - pandas=1.5.2
  - scipy=1.9.3
  - scikit-learn=1.1.3
  - seaborn=0.12.2
  - tqdm=4.63.0
